name: senac-tickets

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - ./apps/web/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:


